# Generated by Django 4.2.1 on 2023-05-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='icon',
            field=models.ImageField(upload_to='categoties_icons', verbose_name='Иконка категории'),
        ),
    ]
