# Generated by Django 4.2.1 on 2023-09-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя партнера')),
                ('image', models.ImageField(upload_to='partner_logos/', verbose_name='Изображение партнера')),
                ('href', models.TextField(verbose_name='ссылка на партнера')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
    ]
