# Generated by Django 4.2.1 on 2023-09-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ourpartners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourpartners',
            name='href',
            field=models.TextField(blank=True, null=True, verbose_name='ссылка на партнера'),
        ),
    ]
