# Generated by Django 4.2.1 on 2023-09-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_ourpartners_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourpartners',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя партнера'),
        ),
    ]
