# Generated by Django 4.2.1 on 2023-09-09 13:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_akcii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название акции')),
                ('image', models.ImageField(upload_to='banner', verbose_name='Главное изображение')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='основной контент')),
                ('href', models.TextField(blank=True, null=True, verbose_name='ссылка на акцию')),
            ],
            options={
                'verbose_name': 'Банер',
                'verbose_name_plural': 'Банеры',
            },
        ),
    ]
