# Generated by Django 4.2.1 on 2023-09-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_banner_akcii'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
