# Generated by Django 4.2.1 on 2023-09-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_albom_photo_albom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='albom',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
