# Generated by Django 4.2.1 on 2023-09-13 13:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_albom_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='preview_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='Краткое описание техники'),
            preserve_default=False,
        ),
    ]
