# Generated by Django 4.2.1 on 2023-09-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_pagecontent_image_importantinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='describe',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
