# Generated by Django 4.2.1 on 2023-09-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_categories_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkciiCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории акции')),
                ('image', models.ImageField(upload_to='important_info/', verbose_name='Главная картинка')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Категория акций',
                'verbose_name_plural': 'Категории акций',
            },
        ),
    ]
