# Generated by Django 4.2.1 on 2023-09-24 09:33

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_akciicategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akcii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='akcii_image/', verbose_name='Главная картинка акции')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='akciicategories',
            name='image',
            field=models.ImageField(upload_to='akcii_category/', verbose_name='Главная картинка'),
        ),
    ]
