# Generated by Django 4.2.1 on 2023-09-24 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_akcii_alter_akciicategories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='akcii',
            name='akciicategories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.akciicategories'),
            preserve_default=False,
        ),
    ]
