# Generated by Django 4.2.1 on 2023-09-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_akcii_akciicategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buklet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='sert/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение буклета',
                'verbose_name_plural': 'Изображения буклета',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Sertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='sert/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Сертификат (диплом)',
                'verbose_name_plural': 'Сертификаты и дипломы',
                'ordering': ['title'],
            },
        ),
    ]
