# Generated by Django 4.2.1 on 2023-09-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_pagecontent_href_pagecontent_on_main_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='href',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Отдельная ссылка'),
        ),
    ]
