# Generated by Django 4.2.1 on 2023-09-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_pagecontent_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Обращение к клиенту')),
                ('telephon', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('is_obr', models.BooleanField(verbose_name='Обработан ли?')),
            ],
            options={
                'verbose_name': 'Обратный звонок',
                'verbose_name_plural': 'Обратные звонки',
                'ordering': ['is_obr'],
            },
        ),
    ]
