# Generated by Django 4.2.1 on 2023-09-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_callback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='is_obr',
            field=models.BooleanField(default=False, verbose_name='Обработан ли?'),
        ),
    ]
