# Generated by Django 4.2.1 on 2023-11-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_callback_is_obr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Обращение к Вам'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='telephon',
            field=models.CharField(max_length=100, verbose_name='Номер Вашего телефона'),
        ),
    ]
