# Generated by Django 4.2.1 on 2023-11-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Расположение пути'),
        ),
    ]
