# Generated by Django 4.2.1 on 2023-12-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_akcii_picture_url_albom_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='akciicategories',
            name='picture_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Расположение главного изображения'),
        ),
    ]
