# Generated by Django 4.2.1 on 2023-12-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_akciicategories_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='on_about_company',
            field=models.BooleanField(default=False, verbose_name='Отображать в разделе о компании?'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='on_main_menu',
            field=models.BooleanField(default=False, verbose_name='Отображать в меню?'),
        ),
    ]
