# Generated by Django 4.2.1 on 2024-02-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_pagecontent_on_about_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='ourpartners',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='VIP'),
        ),
        migrations.AddField(
            model_name='ourpartners',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
