# Generated by Django 4.2.1 on 2024-02-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_post_options_ourpartners_is_vip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='callback',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения'),
        ),
        migrations.AddField(
            model_name='importantinfo',
            name='href',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Отдельная ссылка'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='telephon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер Вашего телефона'),
        ),
    ]
