# Generated by Django 4.2.1 on 2024-02-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_callback_email_callback_message_importantinfo_href_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='preview_description',
        ),
    ]
