# Generated by Django 4.2.1 on 2024-02-24 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_remove_machine_preview_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252, verbose_name='Название категории партнёров')),
            ],
        ),
        migrations.AlterModelOptions(
            name='albom',
            options={'ordering': ['-date'], 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AddField(
            model_name='ourpartners',
            name='category_parners_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.partnerscategory', verbose_name='Категория партнёра'),
        ),
    ]
