# Generated by Django 4.2.1 on 2024-02-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_partnerscategory_alter_albom_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerscategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория партнёров', 'verbose_name_plural': 'Категории партнёров'},
        ),
    ]
